# **Exploring NumPy**

## **1) Introduction to NumPy**



### **A) What is NumPy?**

* NumPy stands for Numerical Python.
* It is a foundational Python library for numerical computing, widely used in nearly every field of science and engineering.
  * NumPy is the universal standard for working with numerical data in Python.
  * It provides powerful tools for linear algebra, statistics, Fourier transforms, and more.
  * The NumPy API is heavily used in libraries like Pandas, Matplotlib, Scikit-learn, and many other data science and machine learning packages.
  * At its core, NumPy provides N-dimensional arrays that store homogeneous data types.
  * These arrays support a wide range of mathematical operations, enabling fast and efficient computation.

### **B) Python Lists vs NumPy Arrays — Full Comparison**

* **1) Speed**
  * Python Lists are slower, whereas NumPy Arrays are much faster.
    * NumPy is implemented in C and uses optimized vectorized operations.
    * Python lists rely on slow interpreted loops.

* **2) Memory Usage**
  * Python Lists occupy more memory, whereas NumPy Arrays are memory efficient.
  * Lists store each item as a separate Python object where as Numpy Array stores elemnents contiguous

* **3) Data Types**
  * Python Lists can hold heterogeneous elements (int, str, float),
  * while NumPy Arrays store only homogeneous data types.

* **4) Mathematical Operations**
  * Python Lists require manual loops for element-wise operations,
  * whereas NumPy Arrays support vectorized operations.

* **5) Multidimensional Support**
  * Python Lists require nested structures and manual looping,
  * while NumPy Arrays provide native and easy support for 2D, 3D, and higher dimensions.
    * NumPy makes matrix/tensor operations straightforward.

* **6) Function Support**
  * Python Lists have limited functionality.
  * NumPy Arrays come with a rich set of built-in functions like mean(), std(), sum(), dot(), etc.

* **7) Broadcasting**
  * Python Lists do not support broadcasting,
  * while NumPy Arrays support automatic broadcasting.

* **8) Memory Contiguity**
  * Python Lists store data in dispersed memory locations,
  * whereas NumPy Arrays store data in contiguous memory blocks.

### **C) Why NumPy Arrays Are Faster Than Python Lists**

* **1) Written in C (Low-Level Optimization)**
  * NumPy is implemented in C and C++

* **2) Vectorization (No Loops in Python Layer)**
  * NumPy uses vectorized operations

* **3) Contiguous Memory Layout**
  * NumPy arrays store data in contiguous memory blocks:

* **4) Homogeneous Data Types**
  * All elements in a NumPy array are of the same data type (e.g., all integers, or all floats).

* **5) Internal Looping in C**
  * When you perform arr * 2, NumPy uses fast internal loops in C, not Python loops.


### **D) Installing and Importing NumPy**


* **1) Install NumPy**
  * If NumPy is not already installed in your environment, use the following command:

    ```
    pip install numpy

    ```

 * If you're using Jupyter Notebook or Google Colab, just run:

    ```
    !pip install numpy

    ```

* **2) Import NumPy**
  * After installation, import NumPy using the standard alias:

    ```
    import numpy as np

    ```

* **3) Check NumPy Version**


In [ ]:
import numpy as np

print(np.__version__)


2.0.2


## **2) Creating NumPy Arrays**
* NumPy offers multiple ways to create arrays
  * From lists or Tuples
  * Using built-in functions
  * Generating values automatically.


### **A) From Python Lists or Tuples**


In [ ]:
# Lab 1: Creating NumPy Arrays using Lists and Tuples

import numpy as np

arr1 = np.array([1, 2, 3])         # 1D array
print(arr1)

print("-"*20)

arr2 = np.array([[1, 2], [3, 4]])  # 2D array (Matrix)
print(arr2)

print("-"*20)

arr3 = np.array([ [[1, 2], [3, 4]],[[5, 6], [7, 8]]])  # 3D array (Tensor)
print(arr3)


[1 2 3]
--------------------
[[1 2]
 [3 4]]
--------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### **B) Using Built-in Array Creation Functions**
* np.zeros(shape)		- Creates an array of all 0s
* np.ones(shape)		- Creates an array of all 1s
* np.full(shape, fill_value)	- Creates an array filled with a specified value


In [ ]:
# Lab 2: Creating Arrays of Zeros (float default)

import numpy as np

arr1 = np.zeros((5,))         # 1D array
print(arr1)

print("-"*20)

arr2 = np.zeros((3,3))         # 2D array
print(arr2)


[0. 0. 0. 0. 0.]
--------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Lab 3: Creating Arrays of Zeros with Integer Data Type

import numpy as np

arr1 = np.zeros((5,),dtype=np.int64)         # 1D array
print(arr1)

print("-"*20)

arr2 = np.zeros((3,3),dtype=np.int64)          # 2D array
print(arr2)


[0 0 0 0 0]
--------------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# Lab 4: Creating Arrays of Ones (float default)

import numpy as np

arr1 = np.ones((5,))         # 1D array
print(arr1)

print("-"*20)

arr2 = np.ones((3,3))         # 2D array
print(arr2)


[1. 1. 1. 1. 1.]
--------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Lab 5: Creating Arrays of Ones with Integer Data Type

import numpy as np

arr1 = np.ones((5,),dtype=np.int64)         # 1D array
print(arr1)

print("-"*20)

arr2 = np.ones((3,3),dtype=np.int64)          # 2D array
print(arr2)


[1 1 1 1 1]
--------------------
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# Lab 6: Creating Arrays with a Specific Fill Value


import numpy as np

arr1 = np.full((5,),9.99)         # 1D array
print(arr1)

print("-"*20)

arr2 = np.full((5,5),99)         # 2D array
print(arr2)


[9.99 9.99 9.99 9.99 9.99]
--------------------
[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


In [ ]:
# Lab 7: Creating Arrays with a Specific Fill Value and Integer Type

import numpy as np

arr1 = np.full((5,),9,dtype=np.int64)         # 1D array
print(arr1)

print("-"*20)

arr2 = np.full((5,5),99,dtype=np.int64)          # 2D array
print(arr2)


[9 9 9 9 9]
--------------------
[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


In [ ]:
# Lab 7A: Creating 3-D Arrays

import numpy as np

myarr = np.full((2,3,5),"Sri")         # 3D array
print(myarr)


[[['Sri' 'Sri' 'Sri' 'Sri' 'Sri']
  ['Sri' 'Sri' 'Sri' 'Sri' 'Sri']
  ['Sri' 'Sri' 'Sri' 'Sri' 'Sri']]

 [['Sri' 'Sri' 'Sri' 'Sri' 'Sri']
  ['Sri' 'Sri' 'Sri' 'Sri' 'Sri']
  ['Sri' 'Sri' 'Sri' 'Sri' 'Sri']]]


### **C) Creating Arrays with Ranges**

* np.arange(start, stop, step)	- Like Python’s range()
* np.linspace(start, stop, num)	- Evenly spaced numbers over a range


In [ ]:
# Lab 8: Creating Arrays using np.arange()

arr1 = np.arange(start=1, stop=10, step=1)
print(arr1)

arr2 = np.arange(1, 11, 2)
print(arr2)

arr3 = np.arange(1, 6)
print(arr3)

arr4 = np.arange(6)
print(arr4)

arr5 = np.arange(-5,10,2)
print(arr5)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 2 3 4 5]
[0 1 2 3 4 5]
[-5 -3 -1  1  3  5  7  9]


In [ ]:
# Lab 9: Creating Arrays using np.linspace()

arr1 = np.linspace(start=1, stop=10,num=10)
print(arr1)

arr2 =np.linspace(1, 10, 5)
print(arr2)

arr3 =np.linspace(1, 2, 5)
print(arr3)

arr3 =np.linspace(1, 2, 25)
print(arr3)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.    3.25  5.5   7.75 10.  ]
[1.   1.25 1.5  1.75 2.  ]
[1.         1.04166667 1.08333333 1.125      1.16666667 1.20833333
 1.25       1.29166667 1.33333333 1.375      1.41666667 1.45833333
 1.5        1.54166667 1.58333333 1.625      1.66666667 1.70833333
 1.75       1.79166667 1.83333333 1.875      1.91666667 1.95833333
 2.        ]


### **D) Array from Existing Array**


In [ ]:
# Lab 10: Copying an Existing NumPy Array

arr = np.array([1, 2, 3])
print(arr)

arr1= arr  # Shallow Copy
print(arr1)

arr2 = np.copy(arr) # Deep Copy
print(arr2)


[1 2 3]
[1 2 3]
[1 2 3]


## **3) NumPy Array Attributes**
* Below are the attributes of NumPy array
  * shape
  * ndim
  * size
  * dtype
  * itemsize
  * nbytes


### **A) shape**
* Returns the Dimensions of the array
* Output is always a tuple


In [ ]:
# Lab 11: Checking Shape of Arrays

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.shape)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)

arr3 = np.array([ [[1, 2], [3, 4]],[[5, 6], [7, 8]]])  # 3D array (Tensor)
print(arr3.shape)

(5,)
(2, 3)
(2, 2, 2)


### **B) ndim**
* Returns the Number of dimensions


In [ ]:
# Lab 12: Checking Number of Dimensions

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.ndim)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.ndim)

arr3 = np.array([ [[1, 2], [3, 4]],[[5, 6], [7, 8]]])  # 3D array (Tensor)
print(arr3.ndim)

1
2
3


### **C) size**
* Returns the number of elements



In [ ]:
# Lab 13: Getting Total Number of Elements

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.size)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.size)

arr3 = np.array([ [[1, 2], [3, 4]],[[5, 6], [7, 8]]])  # 3D array (Tensor)
print(arr3.size)

5
6
8


### **D) dtype**
* Returns the Data type of the elements


In [ ]:
# Lab 14: Getting Data Type of Array Elements

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.dtype)

arr2 = np.array([[1.5, 2.6, 3.9], [4.5, 5.6, 6.7]])
print(arr2.dtype)


int64
float64


### **E) itemsize**
* Returns the  Size of one element in bytes
* Useful for calculating total memory:
  * arr.size * arr.itemsize


In [ ]:
# Lab 15: Size in Bytes of Each Element

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.itemsize)

arr2 = np.array([[1.5, 2.6, 3.9], [4.5, 5.6, 6.7]])
print(arr2.itemsize)


8
8


### **F) nbytes**
* Returns the Total bytes consumed by the array


In [ ]:
# Lab 16: Total Memory Usage in Bytes

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.nbytes)

arr2 = np.array([[1.5, 2.6, 3.9], [4.5, 5.6, 6.7]])
print(arr2.nbytes)


40
48


In [ ]:
# Lab 17: Display All Attributes of a NumPy Array

arr = np.array([[10, 20, 30], [40, 50, 60]])

print("1. Array:\n", arr)
print("2. Shape:", arr.shape)
print("3. Dimensions:", arr.ndim)
print("4. Size:", arr.size)
print("5. Data Type:", arr.dtype)
print("6. Element Size (bytes):", arr.itemsize)
print("7. Total Memory (bytes):", arr.nbytes)

1. Array:
 [[10 20 30]
 [40 50 60]]
2. Shape: (2, 3)
3. Dimensions: 2
4. Size: 6
5. Data Type: int64
6. Element Size (bytes): 8
7. Total Memory (bytes): 48


In [ ]:
# Lab 17A: Display All Attributes of a NumPy 3-D Array

arr = np.array(
    [
     [[10, 20, 30], [40, 50, 60]],
     [[11, 22, 33], [44, 55, 66]],
     [[1, 2, 3], [4, 5, 6]],
    ]
               )

print("1. Array:\n", arr)
print("2. Shape:", arr.shape)
print("3. Dimensions:", arr.ndim)
print("4. Size:", arr.size)
print("5. Data Type:", arr.dtype)
print("6. Element Size (bytes):", arr.itemsize)
print("7. Total Memory (bytes):", arr.nbytes)

1. Array:
 [[[10 20 30]
  [40 50 60]]

 [[11 22 33]
  [44 55 66]]

 [[ 1  2  3]
  [ 4  5  6]]]
2. Shape: (3, 2, 3)
3. Dimensions: 3
4. Size: 18
5. Data Type: int64
6. Element Size (bytes): 8
7. Total Memory (bytes): 144


## **4) Reshaping NumPy Arrays**
* NumPy allows you to change the shape of an existing array without changing its data.
* Two most common methods:
  * **reshape()** – Changes the shape to a specified new shape.
  * **flatten()** – Converts any multi-dimensional array into a 1D array.

### **A) reshape()**
* Returns a new view or copy of the array with the desired shape.
* Total number of elements must remain the same.

  * **arr.reshape(new_shape)**

In [ ]:
 # Lab 18: Reshaping Arrays using reshape()

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print("Original 1D array:")
print(arr)

print("-" * 20)

arr1 = arr.reshape((2, 3))
print("Reshaped to 2x3:")
print(arr1)

print("-" * 20)

arr2 = arr.reshape((3, 2))
print("Reshaped to 3x2:")
print(arr2)

print("-" * 20)

arr3 = arr.reshape((6, 1))
print("Reshaped to 6x1:")
print(arr3)

print("-" * 20)

arr4 = arr.reshape((1, 6))
print("Reshaped to 1x6:")
print(arr4)

# arr5 = arr.reshape((2,2)) # ValueError: cannot reshape array of size 6 into shape (2,2)

Original 1D array:
[1 2 3 4 5 6]
--------------------
Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]
--------------------
Reshaped to 3x2:
[[1 2]
 [3 4]
 [5 6]]
--------------------
Reshaped to 6x1:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
--------------------
Reshaped to 1x6:
[[1 2 3 4 5 6]]


In [ ]:
# Lab 18A: Reshape example
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 9, 9, 10, 11, 12])

arr2d = arr.reshape((3,4))
print(arr2d)
print("-" * 20)

arr3d = arr.reshape((2,3,2))
print(arr3d)
print("-" * 20)


[[ 1  2  3  4]
 [ 5  6  7  9]
 [ 9 10 11 12]]
--------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  9]
  [ 9 10]
  [11 12]]]
--------------------


In [ ]:
# Lab 19: Using -1 in Reshape

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 9, 9, 10, 11, 12])

arr1 = arr.reshape((-1, 2))  # Automatically computes rows
print(arr1)
print("-" * 20)

arr2 = arr.reshape((-1, 3))  # Automatically computes rows
print(arr2)
print("-" * 20)

arr3 = arr.reshape((-1, 6))  # Automatically computes rows
print(arr3)
print("-" * 20)

arr4 = arr.reshape((3, -1))    # Automatically computes Columns
print(arr4)

# arr5 = arr.reshape((-1, -1))   #ValueError: can only specify one unknown dimension


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  9]
 [ 9 10]
 [11 12]]
--------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  9  9]
 [10 11 12]]
--------------------
[[ 1  2  3  4  5  6]
 [ 7  9  9 10 11 12]]
--------------------
[[ 1  2  3  4]
 [ 5  6  7  9]
 [ 9 10 11 12]]


### **B) flatten()**
* Returns a 1D copy of the array.

  * **arr.flatten()**

In [ ]:
# Lab 20: Flattening Multi-dimensional Arrays

import numpy as np

arr2d = np.array([[1, 2], [3, 4]])
print("Original 2D array:")
print(arr2d)

print("-" * 20)

arr1d = arr2d.flatten()
print("Flattened array:")
print(arr1d)


Original 2D array:
[[1 2]
 [3 4]]
--------------------
Flattened array:
[1 2 3 4]


In [ ]:
# Lab 21: Flattening a 3D Array

import numpy as np

# Create a 3D array (2 blocks, 2 rows, 3 columns)
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print("Original 3D Array:")
print(arr3d)

print("-" * 30)

# Flatten it to 1D
arr1d = arr3d.flatten()
print("Flattened 1D Array:")
print(arr1d)

Original 3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
------------------------------
Flattened 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## **5) Indexing and Slicing NumPy Arrays**
* Indexing and slicing help you access and manipulate elements, rows, columns, or sub-arrays efficiently.

### **A) Indexing in 1D Arrays**


In [ ]:
# Lab 22: Indexing on 1D Array

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[0])
print(arr[2])
print("First element:", arr[-6])
print("Last element:", arr[-1])

10
30
First element: 10
Last element: 60


### **B) Slicing in 1D Arrays**


In [ ]:
# Lab 23: Slicing a 1D Array

import numpy as np

arr = np.array([10, 20, 30, 40, 50,60])

print(arr[::])

print(arr[1:5])
print(arr[2:])
print(arr[:3])
print(arr[::2])
print(arr[::-1])


[10 20 30 40 50 60]
[20 30 40 50]
[30 40 50 60]
[10 20 30]
[10 30 50]
[60 50 40 30 20 10]


### **C) Indexing in 2D Arrays**


In [ ]:
# Lab 24: Indexing in 2D Arrays

import numpy as np

arr2d = np.array([[10, 20, 30], [40, 50, 60],[70, 80, 90]])

print(arr2d[0, 1])
print(arr2d[0, 2])

print(arr2d[1, 0])
print(arr2d[1, 2])

print(arr2d[2, 0])
print(arr2d[2, 2])


20
30
40
60
70
90


### **D) Slicing in 2D Arrays**


In [ ]:
# Lab 25: Slicing in 2D Arrays

import numpy as np

arr2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr2d[0:3,0:3])
print("-"*20)

print(arr2d[:,:])
print("-"*20)

print(arr2d[1:, 1:])
print("-"*20)

print(arr2d[:2, :2])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
--------------------
[[10 20 30]
 [40 50 60]
 [70 80 90]]
--------------------
[[50 60]
 [80 90]]
--------------------
[[10 20]
 [40 50]]


### **E) Indexing in 3D Arrays**


In [ ]:
# Lab 26: Indexing in a 3D Array

import numpy as np

arr3d = np.array([
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]]
])

print(arr3d[0, 0, 0])
print(arr3d[0, 1, 1])

print(arr3d[1, 0, 1])
print(arr3d[1, 1, 1])


10
40
60
80


### **F) Slicing in 3D Arrays**


In [ ]:
# Lab 27: Slicing in a 3D Array

import numpy as np

arr3d = np.array([
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]]
])

print(arr3d[0])

print("-"*20)

print(arr3d[1])

print("-"*20)

print(arr3d[0:2, 0:2, 0])

print("-"*20)

print(arr3d[0:2, 0:2, 1])

print("-"*20)

print(arr3d[0:1, 0:2, 0])

print("-"*20)

print(arr3d[0:1, 0:2, 1])

print("-"*20)

print(arr3d[1:2, 0:2, 0])

print("-"*20)

print(arr3d[1:2, 0:2, 1])

print("-"*20)

print(arr3d[1:2, :, 1])



[[10 20]
 [30 40]]
--------------------
[[50 60]
 [70 80]]
--------------------
[[10 30]
 [50 70]]
--------------------
[[20 40]
 [60 80]]
--------------------
[[10 30]]
--------------------
[[20 40]]
--------------------
[[50 70]]
--------------------
[[60 80]]
--------------------
[[60 80]]


## **6) Boolean Indexing and Filtering in NumPy**
* Boolean indexing lets you filter elements in a NumPy array based on conditions.
* Instead of using indices like 0, 1, etc., you use a Boolean array (True / False) to pick values.





### **A) Fancy Indexing in NumPy Arrays**


In [ ]:
# Lab 28: Access Multiple Elements by Index List(Fancy Indexing)

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Index positions 1, 3, and 4
result = arr[[2, 4, 5]]
print("Selected elements:", result)


Selected elements: [30 50 60]


In [ ]:

# Lab 29: Fancy Indexing with Negative Indices

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Last three elements using negative indices
result = arr[[-1, -2, -3]]

print("Selected elements:", result)

result = arr[[-1, 2, -3, 0]]

print("Selected elements:", result)

Selected elements: [60 50 40]
Selected elements: [60 30 40 10]


In [ ]:
# Lab 30: Selecting Specific Rows (Fancy Indexing)

import numpy as np

arr2d = np.array([
    [10, 20],
    [30, 40],
    [50, 60],
    [70, 80]
])

# Select rows at index 0 and 2
result = arr2d[[0, 2]]

print("Selected rows:\n", result)

Selected rows:
 [[10 20]
 [50 60]]


### **B) Filtering with Conditions**


In [ ]:
# Lab 31: Filtering 1D Array with a Condition

import numpy as np

arr = np.array([10, 20, 30, 40, 50,60])

# Condition
condition = arr > 30
print("Boolean mask:", condition)

# Filtering
result = arr[arr > 30]
print("Filtered Array:", result)

x = arr[[True,False,True,False,True,False]]
print(x)

Boolean mask: [False False False  True  True  True]
Filtered Array: [40 50 60]
[10 30 50]


In [ ]:
# Lab 32: Using Multiple Conditions

import numpy as np

arr = np.array([11, 20, 30, 40, 50,61])

# Between 20 and 50 (inclusive)
condition =(arr >= 20) & (arr <= 40)
print("Boolean mask:", condition)

# Filtering
result = arr[(arr >= 20) & (arr <= 40)]
print("Filtered Array:", result)

# Filtering
even_odd = arr[(arr % 2 == 0)]
print("Filtered Array:", even_odd)

Boolean mask: [False  True  True  True False False]
Filtered Array: [20 30 40]
Filtered Array: [20 30 40 50]


In [ ]:
# Lab 33: Boolean Indexing on 2D Array

import numpy as np

arr2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Filter all elements > 50

condition = arr2d > 50
print("Boolean mask:", condition)

result = arr2d[arr2d > 60]
print("Filtered values:", result)

Boolean mask: [[False False False]
 [False False  True]
 [ True  True  True]]
Filtered values: [70 80 90]


### **C) Filtering Using np.where()**


In [ ]:
# Lab 34: Filtering Using np.where()

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Condition
indices = np.where(arr > 30)
print("Indices where arr > 30:", indices)

# Filtering using those indices
result = arr[indices]
print("Filtered Array:", result)


Indices where arr > 30: (array([3, 4, 5]),)
Filtered Array: [40 50 60]


In [ ]:
# Lab 35: Filtering Using np.where()

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Condition: Between 20 and 40 (inclusive)
indices = np.where((arr >= 20) & (arr <= 40))
print("Indices where 20 ≤ arr ≤ 40:", indices)

# Filter using those indices
result = arr[indices]
print("Filtered (between 20 and 40):", result)


Indices where 20 ≤ arr ≤ 40: (array([1, 2, 3]),)
Filtered (between 20 and 40): [20 30 40]


In [ ]:
# Lab 36: Filtering Using np.where()

import numpy as np

arr2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Get positions where values > 50
indices = np.where(arr2d > 50)
print("Indices where arr2d > 50:", indices)

result = arr2d[indices]
print("Filtered values (>50):", result )


Indices where arr2d > 50: (array([1, 2, 2, 2]), array([2, 0, 1, 2]))
Filtered values (>50): [60 70 80 90]


### **D) Replacing Elements using Boolean Mask**


In [ ]:
# Lab 37: Conditional Replacement

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Replace all elements > 30 with 0
print("Filtered Array:\n", arr[arr > 30])

arr[arr > 30] = 999
print("Modified array:", arr)
print("Original array:", arr)


Filtered Array:
 [40 50 60]
Modified array: [ 10  20  30 999 999 999]
Original array: [ 10  20  30 999 999 999]


In [ ]:
# Lab 38: Conditional Replacement in 1D Array

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Replace values > 30 with 999, else keep original
result = np.where(arr > 30, 999, arr)

print("Modified array:", result)
print("Original array:", arr)


Modified array: [ 10  20  30 999 999 999]
Original array: [10 20 30 40 50 60]


In [ ]:
#  Lab 39: Replace Even Numbers with -1, Odd with +1

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# If even → replace with -1, else +1
result = np.where(arr % 2 == 0, -1, +1)

print("Original array:", arr)
print("Replaced array:", result)


Original array: [1 2 3 4 5 6 7 8 9]
Replaced array: [ 1 -1  1 -1  1 -1  1 -1  1]


## **7) Mathematical Operations in NumPy**
* NumPy provides fast and efficient element-wise mathematical operations without needing loops.
* You can perform operations between:
  * Arrays of the same shape
  * Arrays and scalars
  * Arrays of different shapes using broadcasting
  

### **A) Element-wise Operations**


In [ ]:
# Lab 40: Array vs Array (Same Shape)

import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)
print("Modulus:", arr1 % arr2)
print("Power:", arr1 ** arr2)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
Modulus: [0 0 0]
Power: [   10   400 27000]


### **B) Array vs Scalar Operations (Broadcasting)**


In [ ]:
# Lab 41: Array Vs Scalar

import numpy as np

arr = np.array([10, 20, 30])

print("Add 5:", arr + 5)
print("Multiply by 2:", arr * 2)
print("Square:", arr ** 2)
print("Divide by 5:", arr / 5)

Add 5: [15 25 35]
Multiply by 2: [20 40 60]
Square: [100 400 900]
Divide by 5: [2. 4. 6.]


### **C) Element-wise Operations on 2D Arrays**


In [ ]:
# Lab 42: Matrix Math (Element-wise)

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

print("Addition:\n", a + b)
print("Multiplication:\n", a * b)

Addition:
 [[11 22]
 [33 44]]
Multiplication:
 [[ 10  40]
 [ 90 160]]


### **D) Mathematical Functions**


In [ ]:
# Lab 43: NumPy Math Functions

import numpy as np

arr = np.array([1, 4, 9, 16, 25])

print("Square Root:", np.sqrt(arr))
print("Log Base e:", np.log(arr))
print("Exponential:", np.exp(arr))
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))


Square Root: [1. 2. 3. 4. 5.]
Log Base e: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]


### **E) Aggregate Functions**


In [ ]:
# Lab 44: Aggregation Operations

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Standard Deviation:", np.std(arr))

Sum: 150
Mean: 30.0
Min: 10
Max: 50
Standard Deviation: 14.142135623730951


### **F) Axis-Based Operations (for 2D arrays)**


In [ ]:
# Lab 45: Axis Parameter
# column (axis=0)
# row (axis=1)

import numpy as np

arr2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(np.sum(arr2d))   # Sum of all elements in matrix

print(np.sum(arr2d, axis=0))  # Sum of all elements in each Column
print(np.sum(arr2d, axis=1))  # Sum of all elements in each Row

450
[120 150 180]
[ 60 150 240]


### **G) Axis-Based Operations on 3D Arrays (Tensor)**


In [ ]:
# Lab 46: Using axis on a 3D Array

import numpy as np

# Shape: (2 blocks, 3 rows, 4 columns)
arr3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print("Shape:", arr3d.shape)

# 1. Sum of all the elements
print(np.sum(arr3d))
print("-"*25)

# Sum along axis=0 (sum across blocks)
print(np.sum(arr3d, axis=0))
print("-"*25)

# Sum along axis=1 (sum across rows in each block)
print(np.sum(arr3d, axis=1))
print("-"*25)

# Sum along axis=2 (sum across columns in each row)
print(np.sum(arr3d, axis=2))


Shape: (2, 3, 4)
300
-------------------------
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
-------------------------
[[15 18 21 24]
 [51 54 57 60]]
-------------------------
[[10 26 42]
 [58 74 90]]


## **8) Broadcasting in NumPy Arrays**
* Broadcasting allows NumPy do math on arrays of different shapes by automatically stretching the smaller array to match the larger one.
* You don’t need to reshape or repeat values — NumPy handles it for you.

* **Broadcasting Rules (Made Simple)**
  * Compare shapes from right to left (starting from the last dimension).
  * Two dimensions are compatible if They are equal, or One of them is 1
  * If neither rule works →ValueError will be raised
  

### **A) Scalar Broadcasting**


In [ ]:
# Lab 47: Add a Scalar to a 2D Array

import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = arr + 10
print("Result:\n", result)


Result:
 [[11 12 13]
 [14 15 16]]


### **B) Row Vector Broadcasting**


In [ ]:
# Lab 48: Add 1D Row Vector to 2D Array

import numpy as np

arr = np.array([             # shape (2,3)
    [1, 2, 3],
    [4, 5, 6]
])

row = np.array([10, 20, 30])  # shape (3,)

result = arr + row
print("Result:\n", result)

Result:
 [[11 22 33]
 [14 25 36]]


### **C) Column Vector Broadcasting**


In [ ]:
# Lab 49: Add Column Vector to 2D Array

import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

col = np.array([[10], [20]])  # shape (2,1)

result = arr + col
print("Result:\n", result)

Result:
 [[11 12 13]
 [24 25 26]]


### **D) Incompatible Broadcasting → Error**


In [ ]:
# Lab 50: Shape Mismatch Example

import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20])  # shape (2,)

# This will raise a ValueError
# result = a + b # ValueError: operands could not be broadcast together with shapes (2,3) (2,)


## **9) Matrix Operations in NumPy**

  

### **A) Matrix Addition**


In [ ]:
# Lab 51: Matrix Addition

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = A + B
print("Matrix Addition (A + B):\n", C)


Matrix Addition (A + B):
 [[ 6  8]
 [10 12]]


### **B) Matrix Subtraction**

In [ ]:
# Lab 52: Matrix Subtraction

import numpy as np

A = np.array([[10, 20],
              [30, 40]])

B = np.array([[1, 2],
              [3, 4]])

C = A - B
print(" Matrix Subtraction (A - B):\n", C)

 (A - B):
 [[ 9 18]
 [27 36]]


### **C) Matrix Multiplication**
* There are two types:
  * a) Element-wise Multiplication (Not linear algebra)
             C = A * B

  * b) Matrix Multiplication (Dot Product)
            C = np.dot(A, B)      
            C = A @ B   
  
  * Works when:
    * A.shape = (m, n) and B.shape = (n, p) → result shape (m, p)
          

In [ ]:
# Lab 53: Element-wise Matrix Multiplication

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Element-wise multiplication
C = A * B

print(" Matrix Multiplication (A * B):\n", C)


 Matrix Multiplication (A * B):
 [[ 5 12]
 [21 32]]


In [ ]:
# Lab 54: True Matrix Multiplication (Dot Product)

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])


C1 = np.dot(A, B)
C2 = A @ B

print("Multiplication Using dot():\n", C1)
print("Multiplication Using @:\n", C2)

Multiplication Using dot():
 [[19 22]
 [43 50]]
Multiplication Using @:
 [[19 22]
 [43 50]]


### **D) Matrix Transpose**
* Shape changes from (2, 3) → (3, 2)


In [ ]:
# Lab 55: Matrix Transpose

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Original Matrix:\n", A)
print("using .T:\n", A.T)
print("using np.transpose():\n", np.transpose(A))

Original Matrix:
 [[1 2 3]
 [4 5 6]]
using .T:
 [[1 4]
 [2 5]
 [3 6]]
using np.transpose():
 [[1 4]
 [2 5]
 [3 6]]


## **10) Essential NumPy Utility Functions**


### **1. np.append():**
* Add elements to array

In [1]:
# Lab 56: usning append()

import numpy as np

arr = np.array([10, 20, 30,])
new_arr = np.append(arr, [40, 50])
print("After append:", new_arr)


After append: [10 20 30 40 50]


In [6]:
# Lab 56A: usning append()

import numpy as np

arr = np.array([[10, 20],[30,40],[50,60]])
print(arr.ndim)

arr1 = np.append(arr, [70, 80])
print("After append:", arr1)
print(arr1.ndim)

arr2 = arr1.reshape((4,2))
print("After Reshape:", arr2)
print(arr2.ndim)



2
After append: [10 20 30 40 50 60 70 80]
1
After Reshape: [[10 20]
 [30 40]
 [50 60]
 [70 80]]
2


In [17]:
# Lab 56B: usning append()
# axis=0 => Row-wise
# axis=1 => column-wise

import numpy as np

arr = np.array([[10, 20],[30,40],[50,60]])
print(arr.ndim)

arr1 = np.append(arr, [[70, 80]],axis=0)
print("After append:", arr1)
print(arr1.ndim)

arr2 = np.append(arr, [[70],[80],[90]],axis=1)
print("After append:", arr2)
print(arr2.ndim)


2
After append: [[10 20]
 [30 40]
 [50 60]
 [70 80]]
2
After append: [[10 20 70]
 [30 40 80]
 [50 60 90]]
2


### **2. np.delete():**
* Delete elements by index

In [7]:
# Lab 57: usning delete()

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr.ndim)

arr1 = np.delete(arr, 3)
print("After delete:", arr1)
print(arr1.ndim)

1
After delete: [10 20 30 50 60]
1


### **3. np.sort():**
* Sort array (returns a copy)

In [18]:
# Lab 58: usning sort()

arr = np.array([40, 10, 30, 60, 50, 20])

arr1 = np.sort(arr)
print("Sorted array(ASC):", arr1)

arr2 = np.sort(arr)[::-1]
print("Sorted array (DESC):", arr2)


Sorted array(ASC): [10 20 30 40 50 60]
Sorted array (DESC): [60 50 40 30 20 10]


In [19]:
# Lab 59: usning sort()
# For 2D: sort along rows (axis=1) or columns (axis=0)

import numpy as np

arr2d = np.array([
    [40, 30, 10],
    [70, 90, 80],
    [20, 60, 50]
])

arr1 = np.sort(arr2d,axis=1)
print(arr1)

print("-"*15)
arr2 = np.sort(arr2d,axis=0)
print(arr2)


[[10 30 40]
 [70 80 90]
 [20 50 60]]
---------------
[[20 30 10]
 [40 60 50]
 [70 90 80]]


### **4. np.searchsorted():**
* Binary search insert position

In [20]:
# Lab 60: usning sort()
# Returns index where the given element can be inserted to keep array sorted.

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
index = np.searchsorted(arr, 25)
print("Insert index for 25:", index)
print(arr)



Insert index for 25: 2
[10 20 30 40 50]


### **5. np.concatenate():**
* Join arrays

In [21]:
# Lab 61: usning concatenate()

import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([30, 40, 50])
result = np.concatenate((arr1, arr2))

print("Concatenated:\n", result)

Concatenated:
 [10 20 30 30 40 50]


In [24]:
# For 2D, use axis=0 (vertical) or axis=1 (horizontal)
# axis=0 → operate down the rows
# axis=1 → operate across the columns

# Lab 62: Using np.concatenate() on 2D Arrays with Axis


import numpy as np

a = np.array([
    [10, 20],
    [30, 40]
])

b = np.array([
    [50, 60],
    [70, 80]
])


# Vertical Concatenation (row-wise) → axis=0
arr1 = np.concatenate((a, b), axis=0)
print("\n", arr1)

# Horizontal Concatenation (column-wise) → axis=1
arr2 = np.concatenate((a, b), axis=1)
print("\n", arr2)


 [[10 20]
 [30 40]
 [50 60]
 [70 80]]

 [[10 20 50 60]
 [30 40 70 80]]


### **6. np.all():**
* Are all elements True?

In [25]:
# Lab 63: Using np.all()

import numpy as np

arr = np.array([True, True, False])

print("All True?:", np.all(arr))

All True?: False


### **7. np.any():**
* Is at least one element True?

In [26]:
# Lab 64: Using np.any()

import numpy as np

arr = np.array([False, False, True])
print("Any True?:", np.any(arr))

Any True?: True


### **8. np.unique():**
* Get unique values (like SQL DISTINCT)

In [27]:
# Lab 65: Using np.unique()

import numpy as np

arr = np.array([10, 20, 20, 30, 30, 30, 40, 50, 50])
print("Unique values:", np.unique(arr))

Unique values: [10 20 30 40 50]


In [28]:
# Lab 66: Using np.unique() with return_counts=True

import numpy as np

arr = np.array([10, 20, 20, 30, 30, 30, 40, 50, 50])

unique_vals, val_counts = np.unique(arr, return_counts=True)

print("Unique values:", unique_vals)
print("Counts:", val_counts)



Unique values: [10 20 30 40 50]
Counts: [1 2 3 1 2]


### **9. np.isnan():**
* Detect NaN values
* Used in data cleaning pipelines

In [29]:
# Lab 67: Using np.isnan()

import numpy as np

arr = np.array([1.0, np.nan, 2.0])

print("NaN mask:", np.isnan(arr))


NaN mask: [False  True False]


### **10. np.argmax() / np.argmin():**
* Index of max/min

In [31]:
# Lab 68: Using np.argmax() / np.argmin()

import numpy as np

arr = np.array([35, 10, 30, 50, 60, 70 ,20])
print("Max index:", np.argmax(arr))
print("Min index:", np.argmin(arr))

print(arr.min())
print(arr.max())

Max index: 5
Min index: 1
10
70


### **11. np.tile():**
* Repeat an array
* Useful when repeating patterns is needed.

In [34]:
# Lab 69: np.tile()

import numpy as np

arr = np.array([10, 20])
arr1 = np.tile(arr, 3)
print(arr1)
arr2 = arr1.reshape(3,2)
print(arr2)

[10 20 10 20 10 20]
[[10 20]
 [10 20]
 [10 20]]


### **12. np.repeat():**
* Repeat each element

In [35]:
# Lab 70:  np.repeat()

import numpy as np

arr = np.array([10, 20])
print(np.repeat(arr, 3))

[10 10 10 20 20 20]


### **13. np.cumsum() / np.cumprod():**
* Cumulative sum/product

In [36]:
# Lab 71:  np.cumsum() / np.cumprod()

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print("Cumulative sum:", np.cumsum(arr))
print("Cumulative product:", np.cumprod(arr))

Cumulative sum: [ 1  3  6 10 15 21]
Cumulative product: [  1   2   6  24 120 720]


### **14. np.array_equal():**
*  Check full equality

In [41]:
# Lab 72:  np.array_equal()

import numpy as np

a = np.array([10, 20, 30])
b = np.array([10, 20, 30])
c = np.array([10, 20, 30, 40])
d = np.array([10, 20, 50])

print(a==b)
# print(a==c)
print(a==d)

print(np.array_equal(a, b))
print(np.array_equal(a, c))
print(np.array_equal(a, d))


[ True  True  True]
[ True  True False]
True
False
False


### **15. np.round(), np.floor(), np.ceil(), np.trunc():**
* Helpful in data rounding and binning

In [42]:
# Lab 73:  np.round(), np.floor(), np.ceil(), np.trunc()

import numpy as np

arr = np.array([1.234, 2.567])

print(np.round(arr, 1))
print(np.floor(arr))
print(np.ceil(arr))
print(np.trunc(arr))


[1.2 2.6]
[1. 2.]
[2. 3.]
[1. 2.]


### **16. np.argsort():**
* Returns the indices that would sort the array

In [44]:
# Lab 74: Using np.argsort()

import numpy as np

arr = np.array([40, 10, 30, 50, 20])
print("Original array:", arr)

# Get indices that would sort the array
indices = np.argsort(arr)
print("Indices to sort:", indices)

# Sorting using the indices(ASC)
arr1 = arr[indices]
print("Sorted array(ASC):", arr1)

# Sorting using the indices(DESC)
arr2 = arr[indices][::-1]
print("Sorted array(DESC):", arr2)



Original array: [40 10 30 50 20]
Indices to sort: [1 4 2 0 3]
Sorted array(ASC): [10 20 30 40 50]
Sorted array(DESC): [50 40 30 20 10]


### **17. np.clip():**
* Forces all values to stay within a specified min and max.
* Commonly used in:
  * Outlier handling
  * Probability bounds (0 to 1)

In [47]:
# Lab 75: Using np.clip()

import numpy as np

arr = np.array([5, 10, 20, 30, 70, 90, 100])

# Limit values to stay between 18 and 60
clipped = np.clip(arr, 18, 60)

print("Original:", arr)
print("Clipped :", clipped)


Original: [  5  10  20  30  70  90 100]
Clipped : [18 18 20 30 60 60 60]
